language: node_js

node_js:
  - lts/*

install:
  - yarn install # npm ci

script:
  - yarn docs:build # npm run docs:build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $JS_VUE_PRESS # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  keep_history: true
  on:
    branch: 
      - master

notifications:
  slack:
    rooms: 
        - akayhuselfslack:d4w5bX0nSyvQr3SVkMxCLeXB
    template:
      - Deploy %{result} of %{repository}@%{branch} by %{author}
      - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) in %{duration}
      - 'Commit message : %{commit_message}'